### PR TITLE
Use default parameters for client functions

### PR DESCRIPTION
**Pull request by sergioherrera7**
Modified the client functions to use default parameters this way we can avoid duplicated code while using a custom client configuration (https://github.com/psiori/open62541Cpp/pull/5)

Upgrading version to v.1.2.666

### CODE REVIEW

**Comment by ahoereth** [comment]
please always link core prs and vice versa :)

**Review by ahoereth — APPROVED** [review]

**Comment by sergioherrera7** [comment]
This changes are needed for:
https://github.com/psiori/autocrane-core/pull/3107

**Comment by ahoereth** [comment]
approved, please handle accordingly

**Comment by sergioherrera7** [comment]
Lets not delete this branch so this to be available for the autocrane_core/origin/release_ms6 branch

**Pull request merged**
